### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by chadmorita** [CollaborativeStudy/CS#1]
Create a landing page
Add description on landing page.

**Comment by huang6606521** [comment]
1. create a landing page with a brief description about what the web is doing and a login menu.( including pics and words)
2. User Home Page has a menu bar with Home, Profile, Create a Study Session, Join a Study Session etc. 
   <img width="1280" alt="user-home-page" src="https://cloud.githubusercontent.com/assets/21248470/19876053/524757ca-9f76-11e6-813a-b1614dc19067.png">
